version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:rootpass@db:3306/warehouse
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: warehouse
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
